title: Heu_Zz
author:
  name: heuzz
  email: zvxc123@kakao.com
description: >
  profile

show_excerpts: false

minima:
  date_format: "%b %-d, %Y"

  social_links:
    twitter: heuzz
    github:  heuzz

theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
